### ISSUE TITLE
crashing when stopping and starting VR since recent update

### ISSUE THREAD

**Issue by wallminter** [WesleyLuk90/ffxiv-vr#29]
I've been having some crashing issues recently, since I would say one or two version bumps ago. When I stop VR and then restart it, the game crashes and it looks like this:

![image](https://github.com/user-attachments/assets/8f6d4f41-2eaf-402f-900b-f568f2fb925f)

It also sometimes looks a little stuttery if i, say, take my headset off and put it back on, and it either gets fixed when i restart VR, or it crashes. 

i'm using virtual desktop with vdxr to stream to a meta quest 3 from my windows 11 PC with a 4090 and intel 14th series cpu. i have a couple dozen dalamud plugins installed.

I have .tspack files i can share if that would be useful. i don't know if they have any kind of identifying data to the point where i shouldn't post it publicly. i assume not?

**Comment by WesleyLuk90** [comment]
Hard to tell what is going wrong unfortunately since the crash is happening inside the game code. My guess is that it might be related the the graphics settings changing if you configured that? Next time it crashes see if the last few messages are related to the vr plugin.

**Comment by WesleyLuk90** [comment]
If you manage to figure out which setting is causing the crashes you can post it here and I can look into fixing it to make it work.
