### ISSUE TITLE
add labels for sorting issues?

### ISSUE THREAD

**Issue by wallminter** [WesleyLuk90/ffxiv-vr#8]
feel free to close this if you wouldn't find this helpful, but having labels for Bugs vs New Features for these issues might make it easier for you to prioritize things. it would also allow users to filter issues, making it easier to see if a bug they're dealing with has already been reported, or a feature already requested. this becomes more useful the more issues there are

**Comment by WesleyLuk90** [comment]
I've added labels to the current issues
