### ISSUE TITLE
add / commands for macro support

### ISSUE THREAD

**Issue by wallminter** [WesleyLuk90/ffxiv-vr#9]
i use a lot of macros and keyboard shortcuts. there aren't currently a ton of ffxiv-vr options i'd need to set to a macro, but the upcoming "hide body in first person" setting would actually be perfect for this. right now i have a macro assigned to a keypress that switches my HUD to "first person VR combat" mode, and it would be amazing if I could have the macro be like:

```
/hudlayout 3
/vr hidefirstpersonbody 
```

and then when combat is over have another macro i can run that's like:

```
/hudlayout 2
/vr showfirstpersonbody
```
generally i think that the more options exposed to the user as `/` commands, the better

**Comment by George237** [comment]
I do this all the time with voice commands :)
Feels amazing!
I have mapped every console command to a voice command.
Excluding all the mount commands.
https://discord.com/channels/747967102895390741/1169071362158100523
